[package]
name = "randredis"
version = "0.1.0"
authors = ["ankrugold"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.47"
cc = "1.0"

[lib]
crate-type = ["cdylib"]
